name: Lint Commit Messages
on: [pull_request, push]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v4
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - aa-http
          - aa-interop
          - aa-uma
    steps:
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build packages
        run: npm install && npm run bootstrap
      - name: Run tests
        working-directory: ./packages/${{ matrix.package }}
        run: npm test